- name: Build Zetra Engine Only
        # This command specifically excludes the BROKEN sample module
        # so the server doesn't waste time on Unresolved References.
        run: >
          ./gradlew assembleDebug 
          -x :stream-chat-android-ui-components-sample:compileDemoDebugKotlin
          -x :stream-chat-android-ui-components-sample:processDemoDebugResources
          --no-daemon 
          --parallel 
          --build-cache
