name: Build Netscape APK

on:
  push:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle' # Automatically caches gradle dependencies

      - name: Build with Gradle
        run: ./gradlew assembleDebug --no-daemon # No-daemon saves memory on the server
        env:
          JAVA_OPTS: "-Xmx2g" # Limits memory to prevent crashes

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: netscape-chat-debug
          path: stream-chat-android-ui-components-sample/build/outputs/apk/debug/*.apk
